version: 0.2

phases:
  install:
    commands:
      - ls
      - apt-get update -y
      - apt-get install -y zip
  pre_build:
    commands:
      - pip install -r requirements.txt -t ./twitchgamechanger
  build:
    commands:
      - echo Build started on `date`
      - zip -r twitchgamechanger.zip twitchgamechanger/*
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - twitchgamechanger.zip
  discard-paths: yes
